config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: 'projects#index'

  resources :projects, only: [:show]

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'clients' => 'pages#client'


end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/metum.rb
# This class holds meta information for this website :
#
# - headline/slogan
# - banner picture
# - about page content
#

class Metum < ActiveRecord::Base
  mount_uploader :site_banner, BannerUploader

  def self.instance
    first || create
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :project

  validates_presence_of :picture
  validates_presence_of :type

  #scope :bottom_pictures, -> { where(type: 'bottom') }
  #scope :slideshow_pictures, -> { where(type: 'slideshow') }
end

app/models/pictures/bottom.rb
class Bottom < Picture
  mount_uploader :picture, BottomPictureUploader
end

app/models/pictures/slideshow.rb
class Slideshow < Picture
  mount_uploader :picture, SlideshowUploader
end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :banner, BannerUploader

  has_many :bottom_pictures, class_name: "Bottom", :dependent => :destroy
  has_many :slideshow_pictures, class_name: "Slideshow", :dependent => :destroy

  accepts_nested_attributes_for :bottom_pictures, allow_destroy: true
  accepts_nested_attributes_for :slideshow_pictures, allow_destroy: true

  validates_presence_of :title, :description

  scope :published, -> { where(published: true) }
  acts_as_list scope: [:description]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def client

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all.order(position: :asc)
  end

  def show
    @project = Project.find(params[:id])
    @projects = Project.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CpDesign</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <link rel='icon' href='<%= image_path 'cp_favico.png' %>'>
</head>
<body class='<%= params[:action] %>-<%= params[:controller] %>'>
<%= render 'shared/navbar' %>
<%= yield %>

<footer id='footer'>
  <div class="container">
    <a href="/contact">
      <div class="col-sm-6 col-xs-12">
        <h1>
          Contact
        </h1>

        <ul class='infos'>
          <li>CP DESIGN</li>
          <li>28, allée de la ferme</li>
          <li>92170 Vanves</li>
          <li>Map</li>
        </ul>

        <ul class='little-infos'>
          <li>Téléphone +33 (0) 1 41 09 96 93</li>
          <li>Fax +33 (0) 1 41 09 96 94</li>
        </ul>
      </div>
    </a>
    <div class="col-sm-6 col-xs-12">
      <div class="pull-right">
        <ul class='guys'>
          <a href="mailto:c.protat@cp-design.com">
            <li>
              <h3>Christophe Protat</h3>
              <p>c.protat@cp-design.com</p>
            </li>
          </a>
          <a href="mailto:a.rodriguez@cp-design.com">
            <li>
              <h3>Alexandre Rodriguez</h3>
              <p>a.rodriguez@cp-design.com</p>
            </li>
          </a>
        </ul>
      </div>
    </div>

    <div class="oim">
     Dévelopement web -  <a href="http://twitter.com/tchret" target='_blank'>@tchret</a>
    </div>
  </div>
</footer>
<%= javascript_include_tag 'application' %>
<script>
  window.sr = new scrollReveal();
</script>
</body>
</html>

app/views/pages/about.html.erb
<div class="container card-container" id='up'>


  <div class="col-sm-4 lil-card-container" id='team'>

    <div class="card" >
      <header data-color='#000013'><h2>A PROPOS</h2></header>
      <div class="card-body">
        <ul>
          <li>
            <a id='christophe' >Christophe Protat
            <div class="christophe_hidden hidden">

              <p class="info">
                Architecte d’intérieur ENSAAMA
              </p>
              <p class='info'>
                1990 - Co-fondateur MENIBUS & ASSOCIÉ

              </p>
            </a>
            <p class='infos2'>
              <p>
                Agence spécialisée en architecture commerciale et </br>
                communication in store - 25 personnes.</br>
                Directeur général en charge de la création.</br>
                Créateur du concept de théâtralisation magasin avec Carrefour</br>
                Budgets : Carrefour France et Europe- 15 ans de partenariat</br>
                Campagne Anniversaire (35-36 ans) et campagnes de théâtralisation.</br>
                Concept Nationnal Electro-Photo-Ciné-Son, concept international Textile, concept Fleurs,</br>
                Polygone Or - Charte d'identité Groupe.</br>
                Gifi : concept marchand / concept magasin / théâtralisation</br>
                Total Europe : refonte boutique station.</br>
                Concept architectural Coté Sud.</br>
                Relifting graphique fait par Team Créatif</br>
                Adidas/Office Dépot /Le Bourget, Vanity Fair ,Disney.</br>
              </p>
              <p>
                2004 /2006 : TBWA\FULL DESIGN <br>
                Fusion de Ménibus & Associé et \Brand Company, les deux agences design
                du groupe \TBWA - 30 personnes
                Directeur de création Associé
                Budgets : Carrefour France et Europe, Nissan Europe, Nike, Levi's, Dim, Masterfood
              </p>
            </p>
          </div>
          </li>
          <li>
            <a id="alex">Alexandre Rodriguez</a>
            <div class="alex_hidden hidden">
            <p><p>Auguste Thouard & Associés</br>
                Infographiste : CAO / DAO / PAO : Assistance au marketing immobilier
                Responsable de saisie : Animation et formation d’une équipe de 4 personnes
                Responsable de production : Animation et formation d’une équipe de 8 personnes
              </p>
            <p>
              ARCHIMAGE</br>
              Responsable de création
              Budgets : Meunier BNP Parisbas, Insignia-Bourdais, Cogédim, Atisréal Auguste-Thouard, Jones Lang Lasalle,Catella, Dtz Jean-Thouard, Espace consultant,Hill & Associés, Capital & Continental, Pitch promotion.
            </p>
            <p>
              STRATUS <br>
              Chef de Projet conception et exécution
              Budgets : SNCF, Fauchon, LCL, Hammerson, Nexcity,
              Jean paul Gaultier, Parc des expos, Petit Bateau, Opéra Bastille & Garnier, Pathé.
            </p>

            <p>Forus CONCEPT<br>
            Designer
            Médaille d’argent concourt l’épine 2006 / prêt de l’Oséo-Anvar / sélection observer Design 2006
            Participation à la création d’un flacon multiple pivotant
            Domaines d’application : cosmétiques, l’hygiène et l’alimentaire
            Participation à la création d’un interrupteur a barrière optique
            </p>
</p>

</div>
          </li>
        </ul>

      </div>
    </div>
  </div>
  <div class="col-sm-4 lil-card-container" id='recompense'>
    <div class="card">
      <header data-color='#52C1BC'><h2>RECOMPENSES</h2></header>

      <div class="card-body">
        <p>
          <p>
            L’Institût Français du Design remet chaque année un Janus du Commerce  qui récompense les enseignes utilisant le design comme outil de réflexion
            et d’innovation pour humaniser l’acte de commerce et améliorer le confort du consommateur.</br>
          </p>
          <p>
            Le jury attache une grande importance au partenariat entre le commerçant et l’agence. Comme nous !
          </p>
        </p>

        <ul class='hidden-part'>
          <a href="projects/29">
            <li>
              <%= image_tag 'janus2010.png', style: "width:98px"  %>
            </li>
          </a>
          <a href="projects/38">
            <li>
              <%= image_tag 'janus2013.png' %>
            </li>
          </a>
        </ul>

      </div>


    </div>
  </div>
  <div class="col-sm-4 lil-card-container" id='conference'>
    <div class="card">
      <header data-color='#4D7282'><h2>CONFERENCES</h2></header>
      <div class="card-body">
        <div class="hidden-part">
          <iframe width="100%" height="400"
          src="http://www.youtube.com/embed/_ZmZQJ6BUUU?hd=1&rel=0&autohide=1&showinfo=0">
          </iframe>
          <ul class='video_selector'>
            <li data-url='_ZmZQJ6BUUU' class='activeVideo'><%= image_tag 'ifm.png' %></li>
            <li data-url='7C-Bicz1Rqw'><%= image_tag 'mpv.png' %></li>
            <li data-url='x_ZBSerUbUY'><%= image_tag 'siec.png' %></li>
          </ul>
        </div>

        <p>
          <p>
           Nous avons la chance d’être solicité par l’institut Français du Merchandising et l’institut Français du Design pour des conférences en France ou à l’étranger pour exprimer notre vision du commerce.
          </p> </br>
          <p>
            Partager le micro et notre passion avec des spécialistes compétents, rencontrer des nouvelles personnes sont des exercises que nous aimons.
          </p>
        </p>





      </div>

    </div>
  </div>
  <div class="col-sm-4 lil-card-container"  id='presse'>
    <div class="card">
      <header data-color='#ED588B'><h2>PRESSE</h2></header>

      <div class="card-body">
        <div class="hidden-part">
          <iframe width="100%" height="400"
          src="http://www.youtube.com/embed/g5AJ0sgXpjE?hd=1&rel=0&autohide=1&showinfo=0">
          </iframe>
          <ul class='menu'>
            <li><%= image_tag 'france2.png' %></li>
            <li><a href="<%= image_path "NDA_UNO.pdf" %>" download><%= image_tag 'nda.png' %></a></li>
            <li><a href="<%= image_path "ZEPROS-E.LECERC.pdf" %>" download><%= image_tag 'zepros.png' %></a></li>
            <li><a href="<%= image_path "NDA_E.LECERC.pdf" %>" download><%= image_tag 'nda.png' %></a></li>
          </ul>
        </div>
        <p>
          Il arrive que nous prenions la parole dans la presse pour parler tendances retail design dans un journal gratuit distribué à 70 000  ex.</br>

          Il arrive également que nous soyons interviewé au 20 heures.</br>

          Mais la plus part du temps, ce sont les projets de nos clients dont on parle.


        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-4 lil-card-container" id='about'>
    <div class="card">
      <header data-color='#90BF5D'><h2>BLOG</h2></header>
      <div class="card-body">
        <p>
          Nous sommes passionnés, avons la chance de voyager et visiter des magasins partout dans le monde et regarder les choses en complémentarité.</br>
          C’est la raison pour laquelle nous avons co-fondé ce blog avec Pascale Brousse, fondatrice de l’agence Trend sourcing et Frank Rosenthal,expert en marketing du commerce de FRC.
        </p>
        <div class='footer hidden-part'><a href="http://www.nouveaux-concepts.com/">www.nouveaux-concepts.com/</a>
        <%= image_tag 'newconcept.png' %></div>
      </div>
    </div>
  </div>


</div>

app/views/pages/client.html.erb
 <% clients = ['u', 'leclerc', 'gifi', 'botanic', 'comptoir', 'monoprix', 'pharmavie', 'banque_postale', 'uno', 'carrefour', 'oxxo', 'total', 'meyson', 'cash', 'multifood', 'snoke'] %>

<div class='container clients'>

  <% clients.each do |client| %>
    <div class="col-sm-4 client-container">
      <div class="card"> <%= render "shared/client/#{client}" %></div>
    </div>
  <% end %>
    <div class="col-sm-4">
      <div class="card">
        <%= image_tag 'luminarc.png' %>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card">
        <%= image_tag 'rexel.png' %>
      </div>
    </div>
</div>

app/views/pages/contact.html.erb
<div id="map"></div>

<div class='container contact'>
<div class="col-sm-6 col-xs-12">
  <h2>METRO</h2>
  Métro plateau de Vanves VOITURE en sortant du métro prendre à droite, passer tunnel et déboucher dans un jardin public.

  Vous êtes rue Jean Bleuzen, à gauche jusqu'au 26/32

  Passer devant Hachette continuer jusqu'à l'hôtel Adagio

  Entrer dans "l'Allée de la ferme"

  Code grille 1111 E

  1 ere maison à droite

</div>




<div class="col-sm-6 col-xs-12">
  <h2>VOITURE</h2>

  Périphérique extérieur :

  Sortie porte Brancion/Vanves

  Tourner à droite avant le pont SNCF,

  Rentrer dans Vanves

  Vous êtes rue Jean Bleuzen,

  Passer devant Hachette , FR3, Ibis

  Continuer jusqu'à l'hôtel Adagio au 26/32

  de la rue, Entrer dans "l'Allée de la ferme"

  Code grille 2222 E

  1 ere maison à droite



</div>

</div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5kxeSJkQ0Zla0uZiApmS75bQpUISeMP8&sensor=false"></script>

<script type="text/javascript">
  // When the window has finished loading create our google map below
  google.maps.event.addDomListener(window, 'load', init);

  function init() {
      // Basic options for a simple Google Map
      // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
      var mapOptions = {
          // How zoomed in you want the map to start at (always required)
          zoom: 14,
          scrollwheel: false,
             navigationControl: false,
             mapTypeControl: false,
             scaleControl: false,

          // The latitude and longitude to center the map (always required)
          center: new google.maps.LatLng(48.8212469,2.2925661), // New York


          // How you would like to style the map.
          // This is where you would paste any style found on Snazzy Maps.
          styles: [
    {
        "featureType": "all",
        "stylers": [
            {
                "saturation": 0
            },
            {
                "hue": "#e7ecf0"
            }
        ]
    },
    {
        "featureType": "road",
        "stylers": [
            {
                "saturation": -70
            }
        ]
    },
    {
        "featureType": "transit",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "water",
        "stylers": [
            {
                "visibility": "simplified"
            },
            {
                "saturation": -60
            }
        ]
    }
]
      };

      // Get the HTML DOM element that will contain your map
      // We are using a div with id="map" seen below in the <body>
      var mapElement = document.getElementById('map');

      // Create the Google Map using our element and options defined above
      var map = new google.maps.Map(mapElement, mapOptions);
      var image = "<%= image_path 'cp-white.png' %>";
      // Let's also add a marker while we're at it
      var marker = new google.maps.Marker({
          position:  new google.maps.LatLng(48.8212469,2.2925661),
          map: map,
          title: 'CP Design',
          icon: image
      });
  }
</script>

app/views/projects/index.html.erb
<div class='container main-container'>
  <div class="big-logo">
    <%= render 'shared/partials/logo' %>
  </div>
  <header class='home' style='background: url(<%= Metum.last.site_banner %>);background-size: cover; background-position: center center; '>
    <h1><%= Metum.last.slogan %></h1>
  </header>

  <h1 class='title-projects'>Projets</h1>
    <% @projects.each do |project|  %>
      <%= link_to project_path(project) do %>
        <div class='col-sm-3'>
          <div class='study' >
            <div class="sk-spinner sk-spinner-wordpress">
             <span class="sk-inner-circle"></span>
            </div>

          <div class='background lazy' data-original="<%= project.banner%>"  style='background:url(<%= image_path 'grey.gif'%>)'></div>
            <footer>
              <h2>
                <%= project.title %>
              </h2>
              <p> <%= project.country %> <%= project.city %></p>
            </footer>
          </div>
        </div>
      <% end %>
    <% end %>
</div>

app/views/projects/show.html.erb
<% unless Project.all.size < 3 %>

  <div class='nav-project'>
    <div class='title'><%= @project.title %></div>
    <% if Project.exists?(@project.id - 1 ) %>
    <div class='prev'><%= link_to project_path((@project.id - 1) )do %><i class="fa fa-angle-left"> <% end %></i></div>
    <% end %>
    <% if Project.exists?(@project.id + 1 ) %>
      <div class='next'><%= link_to project_path((@project.id + 1) )do %><i class="fa fa-angle-right"> <% end %></i></div>
    <% end %>
    <div class='menu'><i class="fa fa-bars"></i> </div>
    <ul class='menu-index'>
      <% @projects.each do |project| %>
        <% unless project.id == params[:id].to_i %>
          <%= link_to project_path(project) do %><li><%= project.title %></li><% end %>
        <% end %>
      <% end %>
    </ul>

  </div>

<% end %>
<div class='container'>
  <div class='banner' style='background: url(<%= @project.banner %>)'>
  </div>
  <div class='infos'><div class='country'><%=@project.country %></div><div class='description'><%= @project.description %></div></div>
  <div class='content-top-slideshow content'>
    <h1>
      <%= @project.title %>
    </h1>
    <p> <%= @project.pre_slideshow_content.html_safe %></p>
    <div class='slideshow_pictures'>
      <div id="owl-demo" class="owl-carousel owl-theme">

      <% @project.slideshow_pictures.each do |slide| %>
          <div class="item">
            <img src="<%= slide.picture %>"/>
          </div>
      <% end %>
      </div>
    </div>

  <p class='content content-bottom'> <%= @project.post_slideshow_content.html_safe %></p>
  <div class='images_bottom'>
  <% if @project.bottom_pictures.size == 1 %>
    <% @project.bottom_pictures.each do  |image|%>
      <div class="col-xs-12" style='background:url(<%=  image.picture %>)'>
      </div>
    <% end %>
  <% elsif  @project.bottom_pictures.size == 2  %>
    <% @project.bottom_pictures.each do  |image|%>
      <div class="col-xs-6" style='background:url(<%= image.picture %>)'>
      </div>
    <% end %>
  <% elsif @project.bottom_pictures.size == 3 %>

  <% @project.bottom_pictures.each do  |image|%>
    <div class="col-xs-4" style='background:url(<%= image.picture %>)'>
    </div>
  <% end  %>

  <% elsif @project.bottom_pictures.size == 4 %>
    <% @project.bottom_pictures.each do  |image|%>
      <div class="col-xs-3" style='background:url(<%= image.picture %>)'>
      </div>
    <% end %>
  <% end %>

  </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class='nav-container'>
  <nav>
    <ul>
    <%= link_to root_path do %>
      <li>
        Projets
      </li>
    <% end %>
      <a href='/about'>
        <li>
          A propos
        </li>
      </a>
      <a href="/contact">
        <li>
          Contact
        </li>
      </a>

      <a href='/clients'>

        <li>
          CLIENTS
        </li>
      </a>

      <a href="http://www.nouveaux-concepts.com" target="_blank">
        <li>
          BLOG
        </li>
      </a>



    </ul>
    <%= link_to root_path do %>
      <%= render 'shared/partials/logo' %>
    <% end %>
  </nav>
</div>